export const FETCH_INVOICE_LIST = 'FETCH_INVOICE_LIST';
export const FETCH_INVOICE_PAGING = 'FETCH_INVOICE_PAGING';
export const FETCH_INVOICE_MESSAGE = 'FETCH_INVOICE_MESSAGE';
export const ADD_INVOICE = 'ADD_INVOICE';
export const ADD_INVOICE_ERROR = 'ADD_INVOICE_ERROR';
export const FETCHING = 'FETCHING';
export const AUTH_USER = 'AUTH_USER';
